# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12196c09662e45b28563d90ead6be3fef6c5378a837409c692c142db25d01e8ddf8f3fb59432dd1f575b34277c47d7bfdb62233572a9ea5253934712f1af8013

test:
  secret_key_base: 0d4d9e63ec587ac05dcc64d3e74c314855ddcba6e8346da86eade887c710dfc52cce950566c722c6243b5a6365430e06f78af99f6511f6cb2b65759abae7f0b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
